// This file is generated by Slice Machine. Update with care!

import Content from './Content';
import Sant from './Sant';

export {
	Content,
	Sant,
};

export const components = {
	content: Content,
	sant: Sant,
};
